# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: See local directory
        run: ls

      - name: Set VERSION variable from `package.json`
        run: |
          version=`npm pkg get version`
          version="${version//\"/}"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build pixelpainter Docker Image
        run: docker buildx build -f Dockerfile . -t grampacker:v${{ env.VERSION }} -t grampacker:latest

      - name: Check Current Images
        run: docker image ls
